<ZequentCameraLayout>:
    id:camera_layout
    orientation: "horizontal"  
    columns: 3
    ZequentMapView:
        id: mapview
        size_hint: 1,1
        pos: 0,0
    Camera:
        id: camera
        resolution: (640, 480)
        allow_stretch: True
        keep_ratio: True
        play: True
        size_hint: .25,.25
        pos: 0,0
    Button:
        background_color: 0, 0, 0, 0
        size_hint: .25,.25
        pos: 0,0
        on_press: root.test(self)